### ISSUE TITLE
Missing singularity container

### ISSUE THREAD

**Issue by cemmeydan** [ikmb/gwas-assoc#5]
Hi,

The singularity container in the nextflow.config seems to be missing:

```
singularity pull  --name jkaessens-ikmb-gwas-qc-assoc-assets.sif library://jkaessens/ikmb-gwas/qc-assoc-assets.sif
FATAL:   While pulling library image: image jkaessens/ikmb-gwas/qc-assoc-assets.sif:latest (amd64) does not exist in the library
```

The problem also happens during the nextflow run. Looks like it might be the same issue that is present in the gwas-qc issue tracker. 

Thank you.

**Comment by lwienbrandt** [comment]
Hi cemmeydan.
As for the gwas-qc project, we provided a workaround for this issue. Please see the updated Readme.
Thanks and sorry again for the inconvenience.
Lars
P.S.: Please leave a feedback if the workaround solves this issue, thx.
